 const map_data = {
    "India": "IN",
    "Tamil Nadu": "IN-TN",
    "Karnataka": "IN-KA",
    "Andhra Pradesh": "IN-AP",
    "Telangana": "IN-TG",
    "Delhi": "IN-DL",
    "Maharashtra": "IN-MH",
    "West Bengal": "IN-WB",
    "Uttar Pradesh": "IN-UP",
    "Kerala": "IN-KL",
    "Rajasthan": "IN-RJ",
    "Gujarat": "IN-GJ",
    "Punjab": "IN-PB",
    "Haryana": "IN-HR",
    "Bihar": "IN-BR",
    "Madhya Pradesh": "IN-MP",
    "Chhattisgarh": "IN-CT",
    "Orissa": "IN-OR",
    "Assam": "IN-AS",
    "Jharkhand": "IN-JH",
    "Himachal Pradesh": "IN-HP",
    "Uttarakhand": "IN-UT",
     "Uttaranchal": "IN-UT",
    "Goa": "IN-GA",
    "Jammu and Kashmir": "IN-JK",
    "Ladakh": "IN-JK",
    "Tripura": "IN-TR",
    "Meghalaya": "IN-ML",
    "Manipur": "IN-MN",
    "Nagaland": "IN-NL",
    "Arunachal Pradesh": "IN-AR",
    "Mizoram": "IN-MZ",
    "Sikkim": "IN-SK"
  };